### ISSUE TITLE
CHROMEDRV_PATH has a diferent path than the CHROMEDRIVER exc.

### ISSUE THREAD

**Issue by letoss** [enkidulan/chromedriver#1]
I'm importing the CHROMEDRV_PATH and has this path:
'/home/myuser/env/local/lib/python2.7/site-packages/CHROMEDRIVER'

But the real path is:
'/home/myuser/env/CHROMEDRIVER'

**Comment by enkidulan** [comment]
Thank you for report. 

This problem appears on using pip to install package, it seems to be related to [package data installation](https://docs.python.org/2/distutils/setupscript.html#installing-package-data):

> warning: install_data: setup script did not provide a directory for '/tmp/pip-95f85yls-build/chromedriver> /CHROMEDRIVER' -- installing right in '/home/.../.local'

I have tried to add 'data_files' and 'package_data' but it haven't affect anything. I would appreciate any help on this.

BTW,  with easy_install it works fine.

**Comment by letoss** [comment]
I used easy_install and works as you said. Unfortunately I'm not good with packages and pip to help you. Maybe is a good idea add the recommendation to use easy_install instead pip in the wiki.
Regards

**Comment by jmansilla** [comment]
For providing executable binaries,  I think the preferred option would be to put them on the ENV bin folder.
Maybe you can use entry_points (example here https://github.com/machinalis/iepy/blob/develop/setup.py )

Finally, for including package data, you may need to add a Manifest.in file (example here https://github.com/machinalis/iepy/blob/develop/MANIFEST.in)

**Comment by quietlyconfident** [comment]
+1

**Comment by enkidulan** [comment]
I just have made a major release with switching on using wheels - https://pypi.python.org/pypi/chromedriver/2.24.1. That should fix current issues.
